const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {mkdtempSync,rmSync}=require('node:fs');
const {tmpdir}=require('node:os');
const dir=mkdtempSync(tmpdir()+'/gather-test-');
let server,student,admin,id;
async function req(path,method='GET',body,token){const r=await fetch('http://localhost:3107/api'+path,{method,headers:{'Content-Type':'application/json','x-token':token||''},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()}}
before(async()=>{server=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:'3107',DB_PATH:dir+'/test.db',GEMINI_API_KEY:'',GOOGLE_CLIENT_ID:'',GOOGLE_CLIENT_SECRET:'',ADMIN_PASSWORD:'test-password'},stdio:'ignore'});for(let i=0;i<100;i++){try{await fetch('http://localhost:3107');break}catch{await new Promise(r=>setTimeout(r,50))}}student=(await req('/login','POST',{role:'student',studentId:'S004'})).data.token;admin=(await req('/login','POST',{role:'admin',password:'test-password'})).data.token});
after(async()=>{server.kill();await new Promise(r=>server.once('exit',r));rmSync(dir,{recursive:true,force:true})});
test('authorization and session identity',async()=>{assert.equal((await req('/events')).status,401);assert.equal((await req('/stats','GET',null,student)).status,403);assert.equal((await req('/me','GET',null,student)).data.studentId,'S004');assert.equal((await req('/login','POST',{role:'unknown'})).status,400)});
test('CRUD, registration, capacity, cancellation and rebooking',async()=>{const event={name:'Integration Test Workshop',description:'Test event',date:'2030-11-18',time:'10:00',venue:'Lab',max_capacity:1};assert.equal((await req('/events','POST',{...event,date:'2030-02-30'},admin)).status,400);assert.equal((await req('/events','POST',{...event,time:'25:00'},admin)).status,400);id=(await req('/events','POST',event,admin)).data.event_id;assert.ok(id);assert.equal((await req('/events','POST',event,student)).status,403);const booking=await req(`/events/${id}/register`,'POST',null,student);assert.equal(booking.data.ok,true);assert.equal((await req(`/events/${id}/register`,'POST',null,student)).status,400);const other=(await req('/login','POST',{role:'student',studentId:'S003'})).data.token;assert.equal((await req(`/events/${id}/register`,'POST',null,other)).status,400);assert.equal((await req('/my-registrations/'+booking.data.registration_id,'DELETE',null,other)).status,404);assert.equal((await req('/my-registrations/'+booking.data.registration_id,'DELETE',null,student)).status,200);assert.equal((await req(`/events/${id}/register`,'POST',null,student)).data.ok,true);assert.equal((await req('/events/'+id,'PUT',{...event,max_capacity:0},admin)).status,400);assert.equal((await req('/events/'+id,'PUT',{...event,name:'Updated workshop',max_capacity:2},admin)).status,200);assert.equal((await req('/events/'+id+'/participants','GET',null,admin)).data.length,1);assert.equal((await req('/events/'+id,'DELETE',null,admin)).status,200);assert.equal((await req('/events/'+id,'GET',null,student)).status,404)});
test('demo assistant reads database, registers and enforces role',async()=>{const event={name:'Demo Agent Testing',description:'Agent test',date:'2030-11-20',time:'11:00',venue:'Lab',max_capacity:2};const id=(await req('/events','POST',event,admin)).data.event_id;try{const r=await req('/agent','POST',{message:'Register me for the Demo Agent Testing'},student);assert.equal(r.data.mode,'demo');assert.equal(r.data.action,'register_me');assert.match(r.data.reply,/You are registered/);const count=await req('/agent','POST',{message:'How many students have registered for Demo Agent Testing?'},admin);assert.match(count.data.reply,/1 confirmed/);assert.equal((await req('/agent','POST',{message:'Register me for the Demo Agent Testing'},admin)).data.reply,'Sign in as a student to register for an event.');assert.equal((await req('/agent','POST',{message:''},student)).status,400)}finally{await req('/events/'+id,'DELETE',null,admin)}});
test('calendar save requires an owned confirmed student registration',async()=>{assert.equal((await req('/my-registrations/999999/calendar','POST',null,student)).status,404);assert.equal((await req('/my-registrations/1/calendar','POST',null,admin)).status,403);assert.equal((await req('/my-registrations/1/calendar','POST',null,student)).status,404)});
test('OAuth requires administrator and state; logout invalidates session',async()=>{assert.equal((await req('/calendar/connect','POST',null,student)).status,403);assert.equal((await req('/calendar/connect','POST',null,admin)).status,503);assert.equal((await fetch('http://localhost:3107/auth/google/callback?code=fake&state=fake')).status,400);await req('/logout','POST',null,student);assert.equal((await req('/me','GET',null,student)).status,401)});
