const {test,expect}=require('@playwright/test');
test('student journey, assistant and responsive layout',async({page})=>{
 await page.goto('/');await page.locator('#credential').fill('S001');await page.getByRole('button',{name:'Let’s get started'}).click();await expect(page.getByRole('heading',{name:/welcome back/})).toBeVisible();
 await page.locator('.nav').filter({hasText:'Discover events'}).click();await expect(page.locator('.event')).toHaveCount(6);await page.getByRole('button',{name:'Business',exact:true}).click();await expect(page.locator('.event')).toHaveCount(1);await page.getByRole('button',{name:'All events',exact:true}).click();await page.getByRole('textbox',{name:'Search events'}).fill('Startup');await expect(page.locator('.event')).toHaveCount(1);
 await page.locator('.nav').filter({hasText:'AI assistant'}).click();await page.getByRole('textbox',{name:'Message the assistant'}).fill('How many students have registered?');await page.getByRole('button',{name:'Send ↗',exact:true}).click();await expect(page.locator('.message').last()).toContainText('confirmed registrations');
 await page.locator('.nav').filter({hasText:'My schedule'}).click();await page.route('**/api/my-registrations/*/calendar',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,alreadySaved:false})}));await page.getByRole('button',{name:'Calendar',exact:true}).first().click();await expect(page.locator('#toast')).toHaveText('Saved in the connected Google Calendar.');
 await page.reload();await expect(page.getByRole('heading',{name:/welcome back/})).toBeVisible();await page.screenshot({path:'docs/dashboard-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await expect(page.locator('.hero')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await page.screenshot({path:'docs/dashboard-mobile.png',fullPage:true});
});
test('admin creates edits and deletes event',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Administrator',exact:true}).click();await page.locator('#credential').fill('admin123');await page.getByRole('button',{name:'Let’s get started'}).click();await page.locator('.nav').filter({hasText:'Manage events'}).click();await page.getByRole('button',{name:'+ Create event'}).click();await page.locator('[name=name]').fill('Browser test event');await page.locator('[name=date]').fill('2030-10-10');await page.locator('[name=time]').fill('12:00');await page.locator('[name=venue]').fill('Main hall');await page.getByRole('button',{name:'Publish event'}).click();await expect(page.locator('dialog')).not.toBeVisible();const row=page.getByRole('row').filter({hasText:'Browser test event'});await expect(row).toBeVisible();await row.getByRole('button',{name:'Edit',exact:true}).click();await page.locator('[name=name]').fill('Browser test updated');await page.getByRole('button',{name:'Save changes'}).click();const updated=page.getByRole('row').filter({hasText:'Browser test updated'});await expect(updated).toBeVisible();await updated.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Confirm',exact:true}).click();await expect(updated).toHaveCount(0);
});
